name: xmake

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.clang-format'
      - '.clangd'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/cmake.yml'
      - '**/CMakeLists.txt'
      - '.github/workflows/docs.yml'
      - CMakePresets.json

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2025, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-xmake-${{ matrix.os }}
        cancel-in-progress: true

    steps:
      - name: Maximize build space
        if: matrix.os == 'ubuntu-24.04'
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Setup cuda
        if: matrix.os == 'ubuntu-24.04'
        uses: Jimver/cuda-toolkit@v0.2.20
        id: cuda-toolkit
        with:
          cuda: '12.8.1'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 3.0.5
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.os }}

      - name: Xmake configure
        if: matrix.os == 'ubuntu-24.04'
        run: |
          xmake config --yes --github_actions=y

      - name: Xmake configure
        if: matrix.os == 'windows-2025'
        run: |
          xrepo env -y -v -b cuda "xmake config --yes --github_actions=y"

      - name: Build libuipc
        run: |
          xmake build uipc_geometry
          xmake build --jobs=4 cuda
          xmake build --all
